self:
{
  # TODO: think about identification info in json...
  # maybe something like: { device = { id = {}; module = /path; }; }
  # could also add a meta/misc or something too...
  # TODO: rethink...
  common = import ./common self;
  devices = import ./devices self;
}
