self:
{
  # TODO: think about identification info in json...
  # maybe something like: { device = { id = {}; module = /path; }; }
  # could also add a meta/misc or something too...
  # TODO: maybe hidden...
  common = import ./common self;
  # TODO: maybe the only thing consumed...
  devices = import ./devices self;
}
