[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "media-powermenu"
version = "0.0.1"
dependencies = ["pygobject"]

[project.scripts]
media-powermenu = "media_powermenu:main"

[tool.setuptools.packages.find]
where = ["src"]
